aenix-io/etcd-operator

- ADOPTERS.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
demo: https://github.com/aenix-io/etcd-operator/tree/basic-readme
fixes https://github.com/aenix-io/etcd-operator/issues/10
> Fill basic project information

- .github/workflows/docker-publish.yaml
- Dockerfile
1. Union argument layers and copy source code.
2. Changed layers order final image for grow cache hit
> Improve Dockerfile

- api/v1alpha1/etcdcluster_types.go
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/rbac/role.yaml
- internal/controller/etcdcluster_controller.go
- internal/controller/etcdcluster_controller_test.go
Controller now can successfully bootstrap etcd cluster :)
Controller creates Service, ConfigMap and StatefulSet based on EtcdCluster CR
Only EmptyDir storage is supported
Initialized status is being set and updated
fixes https://github.com/aenix-io/etcd-operator/issues/13
> Implementation of basic controller logic

- api/v1alpha1/etcdcluster_types.go
- internal/controller/etcdcluster_controller.go
- internal/controller/etcdcluster_controller_test.go
Update cluster Ready status according to StatefulSet status and update ConfigMap cluster state to `existing` after first time STS is ready
fixes #24
> Implementation of Ready status condition

- internal/controller/etcdcluster_controller.go
- internal/controller/etcdcluster_controller_test.go
in order to access cluster from clients using one IP we decided to use ClusterIP Service
> feat: Create ClusterIP Service for clients access to cluster

- .github/workflows/make-test-e2e.yaml
- .github/workflows/make-test.yaml
> ci: Test ok-to-test only on comment actions

- internal/controller/etcdcluster_controller.go
In case error happens during status update request, reconcile will not be requeued. So, this call should be moved ouside `defer` function
fixes #36
> enh: Update status in reconcile loop, not in defer

- CODEOWNERS
- Makefile
> replace go-install-tool with go install

- api/v1alpha1/etcdcluster_types.go
- api/v1alpha1/etcdcluster_webhook.go
- api/v1alpha1/etcdcluster_webhook_test.go
- config/crd/bases/etcd.aenix.io_etcdclusters.yaml
- internal/controller/factory/statefulset.go
Added `image` field to EtcdCluster spec, added tests and implemented defaulting webhook.
fixes #48
> Add image field to EtcdCluster spec

- internal/controller/etcdcluster_controller.go
- internal/controller/etcdcluster_controller_test.go
- internal/controller/factory/builders.go
- internal/controller/factory/configMap.go
- internal/controller/factory/configmap_test.go
- internal/controller/factory/statefulset.go
- internal/controller/factory/statefulset_test.go
- internal/controller/factory/svc.go
- internal/controller/factory/svc_test.go
> feat: Refactor resource generation

- HOW-TO-START-DEVELOPMENT.md
On kind version 0.22.0, with this command:
`kind load docker-image ghcr.io/aenix-io/etcd-operator:latest`, Kind uses defualt cluster name, but before we created cluster with `--name etcd-operator-kind`
> Fix load docker image doc

- Makefile
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- site/content/en/docs/v0.1/quickstart.md
- site/docker-compose.yaml
> feat: Add quickstart page

- api/v1alpha1/etcdcluster_types.go
- internal/controller/etcdcluster_controller.go
- internal/controller/factory/condition.go
- internal/controller/factory/condition_test.go
- internal/controller/factory/configMap.go
- internal/controller/factory/configmap_test.go
Before that only current statefulset readiness status defined cluster state in configmap.
Checked on local Kind cluster: when using PVC, cluster members can successfully restart without errors. Cluster state in configmap is changed correctly.
> fix: use status condition for setting cluster configmap state

- Makefile
Added commands for local development.
- `make docker-load` builds and loads docker image to local kind cluster
- `make redeploy` rebuilds, loads, deploys manifests and forces controller pods to recreate
Also, I changed default IMG in Makefile to be `ghcr.io`, so that it won't be necessary to change it every time for local testing
> enh: Add common commands for local development

- examples/manifests/etcdcluster-custom-image.yaml
- examples/manifests/etcdcluster-full.yaml
- examples/manifests/etcdcluster-persistent.yaml
- examples/manifests/etcdcluster-resources.yaml
- examples/manifests/etcdcluster-simple.yaml
- examples/manifests/etcdcluster-with-default-pdb.yaml
following up https://github.com/aenix-io/etcd-operator/issues/109#issuecomment-2032847557
Here are examples for:
- Simple cluster with few replicas
- Cluster with custom image
- Cluster with persistent storage
- Cluster with resources
- Cluster with all field specified
> Add EtcdCluster resource examples

- internal/controller/etcdcluster_controller.go
When the cluster is initializing, either a quorum has not yet been established, so if the sts isn't ready, we don't change the reason for etcd not ready, or the cluster has initialized, so we set the status based on the sts state. This reduces the amount of nesting and repeated code in the condition/reason checks.
> Simplify the condition transition rules

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Added `pull_request_target` event. Why not `pull_request`:
"Like how the introduction of Cross-Origin Resource Sharing (CORS) in the browser security model allowed a web site developer to relax the default Same Origin Policy (SOP), the introduction of `pull_request_target` trigger allowed a workflow writer to relax some restrictions to a target repository and must be used carefully. The main differences between the two triggers are:
1. Workflows triggered via `pull_request_target` have write permission to the target repository. They also have access to target repository secrets. The same is true for workflows triggered on `pull_request` from a branch in the same repository, but not from external forks. The reasoning behind the latter is that it is safe to share the repository secrets if …
> add pull_request_target as release-drafter workflow trigger

- internal/controller/factory/builders.go
- internal/controller/factory/configMap.go
- internal/controller/factory/pdb.go
- internal/controller/factory/statefulset.go
- internal/controller/factory/svc.go
Fix https://github.com/aenix-io/etcd-operator/issues/177
> add logging

- site/content/en/docs/v0.2/getting-started/_index.md
Correct link to install:
https://github.com/aenix-io/etcd-operator/releases/latest/download/etcd-operator.yaml
> fix: download link on getting started page

- internal/controller/factory/statefulset.go
- internal/controller/factory/statefulset_test.go
- Changed `ENVTEST_K8S_VERSION` to `1.30.0` as there's no tool chains for version `1.30.1`
- Implemented auto setting `quota-backend-bytes` for requested PVC / emptyDir size
Possible problems:
- After changing requested size, option `quota-backend-bytes` will be left unchanged
fixes #211
> feat: set quota-backend-bytes to 95% of requested size

- .golangci.yml
- examples/manifests/etcdcluster-emptydir.yaml
- internal/controller/factory/statefulset.go
- test/e2e/e2e_test.go
> Add volumeClaimTemplates only if storage.EmptyDir is nil

- .github/workflows/docker-publish.yaml
I'd proceed with using cosign in "keyless" mode, otherwise we'll also need to deal with key management. The root cause of cosign step failures was in rotated TUF root certs: 
- https://github.com/sigstore/cosign/issues/3614#issuecomment-2012521670
- https://blog.sigstore.dev/tuf-root-update/
What about adding verification how-to to README.md: I'd suggest to postpone it until next release, otherwise users might try to verify existing images which will lead to an error:
```
IMG=ghcr.io/aenix-io/etcd-operator:v0.2.0
cosign verify ${IMG} --certificate-identity-regexp '.*' --certificate-oidc-issuer=https://token.actions.githubusercontent.com
Error: no signatures found
main.go:69: error during command execution: no signatures found
```
Fixes: #60
> set cosign-installer to use default (latest) cosign version

- internal/controller/factory/statefulset.go
- internal/controller/factory/statefulset_test.go
Fix non-deterministic order of etcd args.
fixes #248
> fix: sort etcd args to make them deterministic

- internal/controller/factory/statefulset.go
- internal/controller/factory/statefulset_test.go
Set extraArgs in the end of args processing to let them overwrite default values
> Set extraArgs in the end of args processing

- api/v1alpha1/etcdcluster_webhook.go
- api/v1alpha1/etcdcluster_webhook_test.go
- charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
- config/rbac/role.yaml
- examples/manifests/etcdcluster-persistent.yaml
- go.mod
- internal/controller/etcdcluster_controller.go
- internal/controller/factory/pvc.go
- internal/controller/factory/pvc_test.go
- test/e2e/e2e_test.go
fixes https://github.com/aenix-io/etcd-operator/issues/210
Signed-off-by: Andrei Kvapil <kvapss@gmail.com>
> Add resizing operation

- Makefile
- site/content/en/docs/v0.4/reference/api.md
Pre-commit GH actions step can't run successfully without `yq` as a part of the `generate-docs` step in the Makefile. This PR fixes the issue.
> add "yq" as a dependency to "generate-docs" in Makefile

- charts/etcd-operator/templates/rbac/clusterrole-manager-role.yml
- config/rbac/role.yaml
- internal/controller/etcdcluster_controller.go
Fixes these errors: `E0804 17:31:18.410670       1 reflector.go:150] pkg/mod/k8s.io/client-go@v0.30.2/tools/cache/reflector.go:232: Failed to watch *v1.StorageClass: unknown (get storageclasses.storage.k8s.io)`
> Add watch verb for storageclasses rbac

- pkg/set/set.go
This is the first PR in a series of [stacked PRs](https://www.stacking.dev/), aimed ultimately at implementing the features described in #181 and #207. The next PR in the stack can be found at #259.
> Add a helper set library to facilitate implementation of the new health check procedure

- internal/controller/etcdcluster_controller.go
- internal/controller/factory/statefulset.go
- internal/controller/factory/statefulset_test.go
This PR implements the `factory.TemplateStatefulSet` function. The templating was originally carried out as part of the `factory.CreateOrUpdateStatefulSet` function. Almost all of the templating is branchless and is mostly inlined inside of a struct literal. References to the `PodTemplate` field of the `EtcdCluster.Spec` struct were dropped, as premature features that for now only complicate the code, while being non-essential to operating an etcd cluster. When needed, parts of the statefulset template can be factored back out into separate helper functions, much like is already done in e.g. `factory.volumes()` and the possibility of customizing the etcd pod with custom annotations, labels, sidecar containers, etc. can be restored.
> Implement TemplateStatefulSet function
